### ISSUE TITLE
Ajuda um iniciante 

### ISSUE THREAD

**Issue by brunopurper** [lucasrmagalhaes/lucasrmagalhaes#2]
Tem como me dar dicas, de como eu posso focar nos estudos rumo a um dia ser um dev junior?

**Comment by lucasrmagalhaes** [comment]
Devora a plataforma da [DIO](https://digitalinnovation.one/sign-in) e pratica inglês. 
Abraço!

**Comment by lucasrmagalhaes** [comment]
Foi sugerido duas dicas.
