### ISSUE TITLE
Parabenizar

### ISSUE THREAD

**Issue by KellisonSilva** [lucasrmagalhaes/lucasrmagalhaes#3]
Muito bom seu portfolio e todos os outros links de contatos, stackOfflow etc..
Percebi que temos coisas em comum além da programação, trechos da tua historia me fizeram lembrar de como o esforço e dedicação é a chave.

vai demorar bastante pra mim chegar no level equivalente ao o seu, mas vamos lá!!!

Um abraço, seeya.

**Comment by lucasrmagalhaes** [comment]
@KellisonSilva acabei não vendo tua mensagem, porque tu fechou a issue. Muito obrigado! Acredito que tu chega rápido ou mais, só seguir focado. Abração!

**Comment by KellisonSilva** [comment]
@lucasrmagalhaes sigo na estrada...

grande abraço

**Comment by lucasrmagalhaes** [comment]
@KellisonSilva focado em Java, escolheu bem!
