### ISSUE TITLE
oi

### ISSUE THREAD

**Issue by GBRZd4rk** [lucasrmagalhaes/lucasrmagalhaes#5]
oi tem como voce me ajudar com os estudos sou um desenvolvedor iniciante

**Comment by OrangePixelEye** [comment]
@GBRZd4rk oq vc está estudando?

**Comment by lucasrmagalhaes** [comment]
@GBRZd4rk opa! Tudo certo? O que você está estudando?

**Comment by lucasrmagalhaes** [comment]
@GBRZd4rk pode abrir novamente, caso volte. Valeu!
